### ISSUE TITLE
raceback (most recent call last):

### ISSUE THREAD

**Issue by etraeel** [aceknox/FileStreambot#2]
when i run   => python3 -m Ace
i see this errors:
`Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/var/www/html/filestreambot/Ace/__main__.py", line 10, in <module>
    from .bot import StreamBot
  File "/var/www/html/filestreambot/Ace/bot/__init__.py", line 4, in <module>
    from ..vars import Var
  File "/var/www/html/filestreambot/Ace/vars.py", line 10, in <module>
    class Var(object):
  File "/var/www/html/filestreambot/Ace/vars.py", line 18, in Var
    BIN_CHANNEL = int(getenv('BIN_CHANNEL'))
ValueError: invalid literal for int() with base 10: 'directBakhtak'
`

**Comment by aceknox** [comment]
Edit the var

**Comment by aceknox** [comment]
If not fixed contact me on telegram @aceknox
